kafka:
  clusters:
    bootstrapservers: localhost:9092
logging.topic: sera.payapp.logging.out.stdout
task.topic: sera.task.topic
task.result.topic: sera.task.result.topic
axon:
  axonserver:
    servers: axon-server*:8124
  serializer:
    events: jackson
    messages: jackson
    general: xstream
service:
  membership:
    url: http://localhost:8081
server:
  port: 8082

#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    hibernate.ddl-auto: update
axon:
  serializer:
    general: jackson
#  axonserver:
#    servers: localhost:8124